# Generated by Django 5.0.6 on 2024-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primary_type', models.CharField(choices=[('NO', 'Normal'), ('FI', 'Fire'), ('WA', 'Water'), ('EL', 'Electric'), ('GR', 'Grass'), ('IC', 'Ice'), ('FG', 'Fighting'), ('PO', 'Poison'), ('GD', 'Ground'), ('FL', 'Flying'), ('PS', 'Psychic'), ('BG', 'Bug'), ('RK', 'Rock'), ('GH', 'Ghost'), ('DR', 'Dragon'), ('DK', 'Dark'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
