# Generated by Django 5.0.6 on 2024-06-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
