# Generated by Django 5.0.6 on 2024-06-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_species_options_alter_species_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='primary_type',
            new_name='value',
        ),
    ]
