# Generated by Django 5.0.6 on 2024-06-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_rename_primary_type_species_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['id'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('strength', models.IntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.species')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
